# Site settings
title: NoxChen's codeing-blog
email: noxchen@gmail.com  
url: https://noxchen.github.io
description: "stay foolish,stay hungry!"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: NoxChen's blog

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: QQ
    url: 1307792504
  - title: weibo
    url:nox陈
  - title: github
    url: https://github.com/NoxChen

# Build settings
markdown: kramdown
permalink: pretty
