markdown: redcarpet
permalink: /:categories/:title.html
url: 
lsi: false
pygments: true
safe: true
auto: false 

paginate: 8
paginate_path: "page:num"

# presonal config
domain: www.noxchen.com
title: Noxchen's Blog
description: iOS, Cocos2d-x, Lua, reading...
author: Nox Chen
email: noxchen@gmail.com
github: noxchen

config:
  js_dir:
  img_dir:
  css_dir:
